# Eigen Value dan Eigen Vektor

## Konsep 

Eigenvalues (nilai eigen) dan eigenvectors (vektor eigen) adalah konsep yang penting dalam teori matriks dan aljabar linier. Mereka terkait dengan transformasi linear dan matriks, dan memberikan informasi penting tentang sifat-sifat dasar dari matriks.

Eigenvalues bisa berupa bilangan real atau kompleks tergantung pada sifat matriks. Jika sebuah matriks memiliki bilangan kompleks sebagai eigenvalues, maka akan ada pasangan eigenvectors kompleks konjugat yang sesuai. 


## Contoh hitung EigenValue dan EigenVektor

### Matrik 2 x 2

$$
A\=(42​13​)
$$

Untuk menemukan eigenvalue, kita cari λ yang memenuhi:

$$
det(4−λ2 ​13−λ​)\ =0
$$

Menghitung determinan, kita dapatkan:

$$
(4−λ)(3−λ)−2⋅1\=λ2−7λ+10\ =0
$$

Dengan menyelesaikan persamaan kuadrat ini, kita dapatkan dua eigenvalue:

$$
λ1​\=5, λ2​\ =2
$$

In [1]:
import numpy as np

# Definisikan matriks A
A = np.array([[4, 1],
              [2, 3]])

# Hitung eigenvalue dan eigenvektor
eigenvalues, eigenvectors = np.linalg.eig(A)

# Cetak eigenvalue
print("Eigenvalue:")
print(eigenvalues)

# Cetak eigenvektor
print("Eigenvektor:")
print(eigenvectors)


Eigenvalue:
[5. 2.]
Eigenvektor:
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [1]:
import numpy as np

# Definisikan matriks A (3x3)
A = np.array([[4, 1, 2],
              [0, 3, 1],
              [2, 1, 3]])

# Hitung eigenvalue dan eigenvektor
eigenvalues, eigenvectors = np.linalg.eig(A)

# Cetak eigenvalue
print("Eigenvalue:")
print(eigenvalues)

# Cetak eigenvektor
print("Eigenvektor:")
print(eigenvectors)


Eigenvalue:
[5.86619826 1.34455762 2.78924412]
Eigenvektor:
[[ 0.76515114  0.41033692  0.4235206 ]
 [ 0.21209739  0.47151899 -0.88641397]
 [ 0.60791317 -0.78057252  0.18681696]]


### cara menemukan EiganVektor

Untuk menemukan eigenvektor, kita harus terlebih dahulu menemukan eigenvalue dari matriks 
𝐴. Setelah eigenvalue ditemukan, eigenvektor dapat ditentukan dengan menyelesaikan sistem persamaan linear berikut:

$$
(A−λI)v\=0
$$

Di mana 
𝐼
I adalah matriks identitas. Sistem persamaan ini dapat diselesaikan untuk menemukan vektor 𝑣.

Contoh :
Seperti yang kita temukan sebelumnya, eigenvalue 
λ dari 
A adalah 5 dan 2. Untuk mencari eigenvektor yang sesuai dengan masing-masing eigenvalue, kita substitusikan 
λ ke dalam persamaan $$ (A−λI)v\=0. $$

Untuk $ λ\=5: $

$$
(A−5I)v\=(4−52​13−5​)(v1​v2​​)\=(−12​1−2​)(v1​v2​​)\=(00​)
$$

Persamaan ini menghasilkan sistem linear:

$$
−v1​+v2​\=02v1​−2v2​\=0​
$$

Yang berarti v1 = v2. Jadi Eigenvektor yang sesuai $ λ\=5 $ adalah

$$
v1​\=k(11​)untuk sembarang k\=0
$$

Untuk $λ\=2$
$$
(A−2I)v\=(4−22​13−2​)(v1​v2​​)\=(22​11​)(v1​v2​​)\=(00​)
$$

Persamaan ini menghasilkan sistem linear:

$$
2v1​+v2​\=02v1​+v2​\=0​
$$

Yang berarti $$v2\=−2v1v\_2 = -2v\_1v2​\=−2v1​. Jadi, eigenvektor yang sesuai dengan λ\=2 $$ adalah

$$
v2​\=k(1−2​)untuk sembarang k\=0
$$

In [2]:
import numpy as np

# Definisikan matriks A
A = np.array([[4, 1],
              [2, 3]])

# Hitung eigenvalue dan eigenvektor
eigenvalues, eigenvectors = np.linalg.eig(A)

# Cetak eigenvalue
print("Eigenvalue:")
print(eigenvalues)

# Cetak eigenvektor
print("Eigenvektor:")
print(eigenvectors)


Eigenvalue:
[5. 2.]
Eigenvektor:
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


contoh 3 x 3


In [4]:
import numpy as np

# Definisikan matriks A
A = np.array([[4, 1, 2],
              [2, 3, 1],
              [1, 2, 3]])

# Hitung eigenvalue dan eigenvektor
eigenvalues, eigenvectors = np.linalg.eig(A)

# Cetak eigenvalue
print("Eigenvalue:")
print(eigenvalues)

# Cetak eigenvektor
print("Eigenvektor:")
print(eigenvectors)


Eigenvalue:
[6.38417273+0.j         1.80791363+0.80460079j 1.80791363-0.80460079j]
Eigenvektor:
[[ 0.66145094+0.j         -0.39996437-0.35287656j -0.39996437+0.35287656j]
 [ 0.54359285+0.j         -0.20787801+0.45172424j -0.20787801-0.45172424j]
 [ 0.51671023+0.j          0.68427961+0.j          0.68427961-0.j        ]]


Ref : Laily Sabrina Hapsari
https://rpubs.com/bokuwalily/1051528