# Matrix Invers

## Definisi
Invers matriks adalah kebalikan (invers) dari sebuah matriks yang apabila matriks tersebut dikalikan dengan inversnya, akan menjadi matriks identitas. Invers matriks dilambangkan dengan A-1. Suatu matriks dikatakan memiliki invers jika determinan dari matriks tersebut tidak sama dengan nol.

Misal : $
AA^{-1}=A^{-1}A=\begin{bmatrix}
1 & 0\\
0 & 1
\end{bmatrix}
$

Untuk menentukan invers dari sebuah matriks, terdapat dua aturan berdasarkan ordonya, yaitu ordo 2x2 dan ordo 3x3.[1]https://akupintar.id/info-pintar/-/blogs/matriks-pengertian-operasi-determinan-invers-dan-contoh-soal


Rumus untuk mencari invers matrik: $A^{-1} = \frac{1}{\det{\left(A\right)}} \left[\begin{matrix}d&-b\\-c&a\\\end{matrix}\right]$ 

\begin{split}
A^{-1} = \frac{1}{ad-bc} \left[\begin{matrix}d&-b\\-c&a\\\end{matrix}\right]\end{split}

### Sifat-sifat matriks invers

Jika A dan B adalah matriks-matriks yang dapat dibalik dan yang ukurannya sama, maka

1.  $(A^{-1})^{-1} = A$

2.  $A^n$ invertebel dan $(A^n)^{-1} = (A^{-1})^n$

3.  $kA$ adalah matrik invertebel dan $(kA)^{-1} = (\frac{1}{k})A^{-1}$

4.  $A^T$ invertebel dan $(A^T)^{-1} = (A^{-1})^T$

5.  $A$ dan $B$
 keduanya matriks invertibel, maka AB
 invertibel dan $(AB)^{-1} = B^{-1}A^{-1}$

Sebuah hasilkali matriks yang dapat dibalik selalu dapat dibalik, dan invers hasil kali tersebut adalah hasil kali invers dalam urutan yang dibalik. [1]https://jagostat.com/aljabar-linear/definisi-dan-sifat-sifat-invers-matriks



### Solusi persamaan sistem linier dengan matrik invers

Sistem persamaan linier

$2x + 3y = 6$

$4x + 5y = 11$

ubah dalam persamaan matrik:

\begin{split}
\begin{bmatrix}
2 & 3\\
4 & 5
\end{bmatrix}
\begin{bmatrix}
x\\
y
\end{bmatrix}=
\begin{bmatrix}
6\\
11
\end{bmatrix}
\end{split}


Langkah ke pertama: 

\begin{split}
\begin{bmatrix}
x\\
y
\end{bmatrix}=
\begin{bmatrix}
2 & 3\\
4 & 5
\end{bmatrix}^{-1}
\begin{bmatrix}
6\\
11
\end{bmatrix}
\end{split}


Langkah ke-dua:

\begin{split}
\begin{bmatrix}
x\\
y
\end{bmatrix}
=\frac{1}{-2}\begin{bmatrix}
5 & -3\\
-4 & 2
\end{bmatrix}
\begin{bmatrix}
6\\
11
\end{bmatrix}
\end{split}

Langkah ke-tiga:

\begin{split}
\begin{bmatrix}
x\\
y
\end{bmatrix}
=\frac{1}{-2}\begin{bmatrix}
-3\\
-2
\end{bmatrix}
\end{split}

Langkah ke-empat: 

\begin{split}
\begin{bmatrix}
x\\
y
\end{bmatrix}=
\begin{bmatrix}
1.5\\
1
\end{bmatrix}
\end{split}

In [1]:
import numpy as np
A = np.array([[2, 3], [4, 5]])
Ai = np.linalg.inv(A) # menghitung inverse A
b = np.array([[6], [11]])
q = np.dot(Ai, b)
print(q)

[[1.5]
 [1. ]]


### Mencari matriks Invers dengan eliminasi gauss jordan

Metode Gauss-Jordan merupakan salah satu varian dari eliminasi Gaussian yang dilakukan dengan cara operasi reduksi baris untuk mencari invers suatu matriks.

contoh mencari inver =s dengan eliminasi gauss jordan menggunakan matrik dengan ordo 3x3

contoh soal $A = \begin{bmatrix}
1 & 2 & 3\\
0 & 1 & 4 \\
5 & 6 & 0
\end{bmatrix}$


\begin{split}I = \begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}\end{split}

Kemudian gunakan gauss jordan elimination 

$A = \begin{bmatrix}
1 & 2 & 3|1 & 0 & 0\\
0 & 1 & 4|0 & 1 & 0  \\
5 & 6 & 0|0 & 0 & 1
\end{bmatrix}$
 
untuk mencari invers, gimana caranya matriks identitasnya bisa ada disebelah kiri, terserah baris berapa mau di tambahin/dikurangin/dikali/dibagi dengan baris manapun.

Kita kalikan baris pertama dengan 5 kemudian dikurangi baris ketiga $A = \begin{bmatrix}
1 & 2 & 3|1 & 0 & 0\\
0 & 1 & 4|0 & 1 & 0  \\
0 & -4 & -15|-5 & 0 & 1
\end{bmatrix}
$


langkah terakhir kita tinggal kurangkan baris pertama dengan 2x baris kedua.hasilnya : $A = \begin{bmatrix}
1 & 0 & 0|-24 & 18 & 5\\
0 & 1 & 0|20 & -15 & -4  \\
0 & 0 & 1|-5 & 4 & 1
\end{bmatrix}
$

nah yang ada disebelah kanan adalah invers dari matrik A. jadi invers matriknya

\begin{split}A^{-1} = \begin{bmatrix}
-24 & 18 & 5\\
20 & -15 & -4  \\
-5 & 4 & 1
\end{bmatrix}\end{split}

 


In [18]:
import numpy as np

# Membuat Matriks 
A = np.array([(1,2,3),
             (0,1,4),
             (5,6,0)])
I = np.array([(1,0,0),
              (0,1,0),
              (0,0,1)])
print("Matriks A : \n")
print(A)
print("\n Matriks Identitas : \n")
print(I)

Matriks A : 

[[1 2 3]
 [0 1 4]
 [5 6 0]]

 Matriks Identitas : 

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### Code eliminasi gauus jordan


In [19]:
EG = np.array([(1,2,3,1,0,0),
             (0,1,4,0,1,0),
             (5,6,0,0,0,1)])
print(EG)

[[1 2 3 1 0 0]
 [0 1 4 0 1 0]
 [5 6 0 0 0 1]]


 Menambahakan fungsi RowAdd:

In [20]:
def RowAdd(A,k,l,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowAdd akan menghasilkan duplicate dari 
#     array dengan baris k akan di kali dengan 'scale' bukan 0. lalu nilai
#     baris l akan di tambah dengan nilai baris k yang sudah dikalikan  
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

def RowSwap(A,k,l):
# =============================================================================
#     A adalah sebuah NumPy array.  RowSwap akan menghasilkan duplicate dari 
#     array dengan baris k dan l di tukar
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowScale akan menghasilkan duplicate dari 
#     array dengan baris k di kali dengan skalar bukan 0
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

 Kita kurangkan baris ketiga dengan 5x baris pertama

In [21]:
RA = np.array([(1,2,3,1,0,0),
             (0,1,4,0,1,0),
             (5,6,0,0,0,1)])

k = 0
l = 2
scale = -5

result = RowAdd(RA, k, l, scale)
print("Matriks awal:")
print(RA)
print("\nHasil:")
print(result)

Matriks awal:
[[1 2 3 1 0 0]
 [0 1 4 0 1 0]
 [5 6 0 0 0 1]]

Hasil:
[[  1.   2.   3.   1.   0.   0.]
 [  0.   1.   4.   0.   1.   0.]
 [  0.  -4. -15.  -5.   0.   1.]]


 Dari matriks diatas, kita tambahkan baris ke 3 dengan 4kali baris ke dua

In [22]:
RA2 = np.array([(1,2,3,1,0,0),
             (0,1,4,0,1,0),
             (0,-4,-15,-5,0,1)])
k = 1
l = 2
scale = 4

result = RowAdd(RA2, k, l, scale)
print("Matriks awal:")
print(RA2)
print("\nHasil:")
print(result)

Matriks awal:
[[  1   2   3   1   0   0]
 [  0   1   4   0   1   0]
 [  0  -4 -15  -5   0   1]]

Hasil:
[[ 1.  2.  3.  1.  0.  0.]
 [ 0.  1.  4.  0.  1.  0.]
 [ 0.  0.  1. -5.  4.  1.]]


Langkah selanjutnya kurangkan baris kedua dengan 4x baris ketiga

In [23]:
RA3 = np.array([(1,2,3,1,0,0),
             (0,1,4,0,1,0),
             (0,0,1,-5,4,1)])

k = 2
l = 1
scale = -4

result = RowAdd(RA3, k, l, scale)
print("Matriks awal:")
print(RA3)
print("\nHasil :")
print(result)

Matriks awal:
[[ 1  2  3  1  0  0]
 [ 0  1  4  0  1  0]
 [ 0  0  1 -5  4  1]]

Hasil :
[[  1.   2.   3.   1.   0.   0.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]


 kita kurangkan juga baris pertama dengan 3x baris ketiga

In [24]:
RA4 = np.array([(1,2,3,1,0,0),
             (0,1,0,20,-15,-4),
             (0,0,1,-5,4,1)])
k = 2
l = 0
scale = -3

result = RowAdd(RA4, k, l, scale)
print("Matriks awal:")
print(RA4)
print("\nHasil :")
print(result)

Matriks awal:
[[  1   2   3   1   0   0]
 [  0   1   0  20 -15  -4]
 [  0   0   1  -5   4   1]]

Hasil :
[[  1.   2.   0.  16. -12.  -3.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]


 langkah terakhir kita kurangkan baris pertama dengan 2x baris kedua

In [25]:
RA5 = np.array([(1,2,0,16,-12,-3),
             (0,1,0,20,-15,-4),
             (0,0,1,-5,4,1)])
k = 1
l = 0
scale = -2

result = RowAdd(RA5, k, l, scale)
print("Matriks awal:")
print(RA5)
print("\nHasil :")
print(result)

Matriks awal:
[[  1   2   0  16 -12  -3]
 [  0   1   0  20 -15  -4]
 [  0   0   1  -5   4   1]]

Hasil :
[[  1.   0.   0. -24.  18.   5.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]


Maka invers dari matriks A adalah : 
\begin{bmatrix} -24 & 18 & 5\\
 20 & -15 & -4\\ -5 & 4 & 1\\ \end{bmatrix}

###  Penyelesaian sistem persamaan linier menggunakan matriks invers membuat soal 4 persamaan 4 variabel cari solusinya dengan eliminasi gaus 
Buatkan Penyelesaian sistem persamaan dari 


\begin{align*} 4x_1 + 8x_2 + 5x_3 + 4x_4 = 12\\

4x_1 + 5x_2 + 4x_3 + 5x_4 = 15 \\

5x_1 + 4x_2 + 1x_3 + 6x_4 = 9 \\

3x_1 + 5x_2 + 2x_3 + 4x_4 = 5\end{align*} 



\begin{bmatrix} 4 & 8 & 5 & 4\\
 4 & 5 & 4 & 5 \\ 
 5 & 4 & 1 & 6\\ 
 3  & 5 & 2 & 4\\
  \end{bmatrix}

\begin{bmatrix} x1\\
  x2\\ x3  
  \\ x4\end{bmatrix}

\begin{bmatrix} 12 \\ 15 \\ 9 \\ 5 \end{bmatrix}


\begin{align*}= b \\
X = A-1 b \\
x = A- b \\
x = A-1 b \end{align*}
#### Jawaban


In [37]:
import numpy as np
 
A = np.array([[2,3,1,1,1,0,0,0],
              [1,1,5,1,0,1,0,0],
              [3,2,2,4,0,0,1,0],
              [4,1,3,2,0,0,0,1]])
print(A)

[[2 3 1 1 1 0 0 0]
 [1 1 5 1 0 1 0 0]
 [3 2 2 4 0 0 1 0]
 [4 1 3 2 0 0 0 1]]


In [38]:
k = 1
l = 0
scale = -1

h = RowAdd(A, k, l, scale)
print("Matriks awal:")
print(A)
print("\nHasil :")
print(h)

Matriks awal:
[[2 3 1 1 1 0 0 0]
 [1 1 5 1 0 1 0 0]
 [3 2 2 4 0 0 1 0]
 [4 1 3 2 0 0 0 1]]

Hasil :
[[ 1.  2. -4.  0.  1. -1.  0.  0.]
 [ 1.  1.  5.  1.  0.  1.  0.  0.]
 [ 3.  2.  2.  4.  0.  0.  1.  0.]
 [ 4.  1.  3.  2.  0.  0.  0.  1.]]


In [39]:
k = 0
l = 1
scale = -1

h2 = RowAdd(h, k, l, scale)
print("Matriks awal:")
print(h)
print("\nHasil :")
print(h2)

Matriks awal:
[[ 1.  2. -4.  0.  1. -1.  0.  0.]
 [ 1.  1.  5.  1.  0.  1.  0.  0.]
 [ 3.  2.  2.  4.  0.  0.  1.  0.]
 [ 4.  1.  3.  2.  0.  0.  0.  1.]]

Hasil :
[[ 1.  2. -4.  0.  1. -1.  0.  0.]
 [ 0. -1.  9.  1. -1.  2.  0.  0.]
 [ 3.  2.  2.  4.  0.  0.  1.  0.]
 [ 4.  1.  3.  2.  0.  0.  0.  1.]]


In [40]:
k = 0
l = 2
scale = -3

h3 = RowAdd(h2, k, l, scale)
print("Matriks awal:")
print(h2)
print("\nHasil :")
print(h3)

Matriks awal:
[[ 1.  2. -4.  0.  1. -1.  0.  0.]
 [ 0. -1.  9.  1. -1.  2.  0.  0.]
 [ 3.  2.  2.  4.  0.  0.  1.  0.]
 [ 4.  1.  3.  2.  0.  0.  0.  1.]]

Hasil :
[[ 1.  2. -4.  0.  1. -1.  0.  0.]
 [ 0. -1.  9.  1. -1.  2.  0.  0.]
 [ 0. -4. 14.  4. -3.  3.  1.  0.]
 [ 4.  1.  3.  2.  0.  0.  0.  1.]]


In [41]:
k = 0
l = 3
scale = -4

h4 = RowAdd(h3, k, l, scale)
print("Matriks awal:")
print(h3)
print("\nHasil :")
print(h4)

Matriks awal:
[[ 1.  2. -4.  0.  1. -1.  0.  0.]
 [ 0. -1.  9.  1. -1.  2.  0.  0.]
 [ 0. -4. 14.  4. -3.  3.  1.  0.]
 [ 4.  1.  3.  2.  0.  0.  0.  1.]]

Hasil :
[[ 1.  2. -4.  0.  1. -1.  0.  0.]
 [ 0. -1.  9.  1. -1.  2.  0.  0.]
 [ 0. -4. 14.  4. -3.  3.  1.  0.]
 [ 0. -7. 19.  2. -4.  4.  0.  1.]]


In [42]:
k = 1
l = 0
scale = -1

h5 = RowScale(h4, k, scale)
print("Matriks awal:")
print(h4)
print("\nHasil :")
print(h5)

Matriks awal:
[[ 1.  2. -4.  0.  1. -1.  0.  0.]
 [ 0. -1.  9.  1. -1.  2.  0.  0.]
 [ 0. -4. 14.  4. -3.  3.  1.  0.]
 [ 0. -7. 19.  2. -4.  4.  0.  1.]]

Hasil :
[[ 1.  2. -4.  0.  1. -1.  0.  0.]
 [-0.  1. -9. -1.  1. -2. -0. -0.]
 [ 0. -4. 14.  4. -3.  3.  1.  0.]
 [ 0. -7. 19.  2. -4.  4.  0.  1.]]


In [43]:
k = 1
l = 0
scale = -2

h6 = RowAdd(h5, k, l, scale)
print("Matriks awal:")
print(h5)
print("\nHasil :")
print(h6)

Matriks awal:
[[ 1.  2. -4.  0.  1. -1.  0.  0.]
 [-0.  1. -9. -1.  1. -2. -0. -0.]
 [ 0. -4. 14.  4. -3.  3.  1.  0.]
 [ 0. -7. 19.  2. -4.  4.  0.  1.]]

Hasil :
[[ 1.  0. 14.  2. -1.  3.  0.  0.]
 [-0.  1. -9. -1.  1. -2. -0. -0.]
 [ 0. -4. 14.  4. -3.  3.  1.  0.]
 [ 0. -7. 19.  2. -4.  4.  0.  1.]]


In [44]:
k = 1
l = 2
scale = 4

h7 = RowAdd(h6, k, l, scale)
print("Matriks awal:")
print(h6)
print("\nHasil :")
print(h7)

Matriks awal:
[[ 1.  0. 14.  2. -1.  3.  0.  0.]
 [-0.  1. -9. -1.  1. -2. -0. -0.]
 [ 0. -4. 14.  4. -3.  3.  1.  0.]
 [ 0. -7. 19.  2. -4.  4.  0.  1.]]

Hasil :
[[  1.   0.  14.   2.  -1.   3.   0.   0.]
 [ -0.   1.  -9.  -1.   1.  -2.  -0.  -0.]
 [  0.   0. -22.   0.   1.  -5.   1.   0.]
 [  0.  -7.  19.   2.  -4.   4.   0.   1.]]


In [45]:
k = 1
l = 3
scale = 7
h8 = RowAdd(h7, k, l, scale)
print("Matriks awal:")
print(h7)
print("\nHasil :")
print(h8)

Matriks awal:
[[  1.   0.  14.   2.  -1.   3.   0.   0.]
 [ -0.   1.  -9.  -1.   1.  -2.  -0.  -0.]
 [  0.   0. -22.   0.   1.  -5.   1.   0.]
 [  0.  -7.  19.   2.  -4.   4.   0.   1.]]

Hasil :
[[  1.   0.  14.   2.  -1.   3.   0.   0.]
 [ -0.   1.  -9.  -1.   1.  -2.  -0.  -0.]
 [  0.   0. -22.   0.   1.  -5.   1.   0.]
 [  0.   0. -44.  -5.   3. -10.   0.   1.]]


In [46]:
k = 2
l = 2
scale = -1/22

h9 = RowScale(h8, k, scale)
print("Matriks awal:")
print(h8)
print("\nHasil :")
print(h9)

Matriks awal:
[[  1.   0.  14.   2.  -1.   3.   0.   0.]
 [ -0.   1.  -9.  -1.   1.  -2.  -0.  -0.]
 [  0.   0. -22.   0.   1.  -5.   1.   0.]
 [  0.   0. -44.  -5.   3. -10.   0.   1.]]

Hasil :
[[  1.           0.          14.           2.          -1.
    3.           0.           0.        ]
 [ -0.           1.          -9.          -1.           1.
   -2.          -0.          -0.        ]
 [ -0.          -0.           1.          -0.          -0.04545455
    0.22727273  -0.04545455  -0.        ]
 [  0.           0.         -44.          -5.           3.
  -10.           0.           1.        ]]


In [47]:
k = 2
l = 0
scale = -14

h10 = RowAdd(h9, k, l,scale)
print("Matriks awal:")
print(h9)
print("\nHasil :")
print(h10)

Matriks awal:
[[  1.           0.          14.           2.          -1.
    3.           0.           0.        ]
 [ -0.           1.          -9.          -1.           1.
   -2.          -0.          -0.        ]
 [ -0.          -0.           1.          -0.          -0.04545455
    0.22727273  -0.04545455  -0.        ]
 [  0.           0.         -44.          -5.           3.
  -10.           0.           1.        ]]

Hasil :
[[  1.           0.           0.           2.          -0.36363636
   -0.18181818   0.63636364   0.        ]
 [ -0.           1.          -9.          -1.           1.
   -2.          -0.          -0.        ]
 [ -0.          -0.           1.          -0.          -0.04545455
    0.22727273  -0.04545455  -0.        ]
 [  0.           0.         -44.          -5.           3.
  -10.           0.           1.        ]]


In [48]:
k = 2
l = 1
scale = 9

h11 = RowAdd(h10, k, l,scale)
print("Matriks awal:")
print(h10)
print("\nHasil :")
print(h11)

Matriks awal:
[[  1.           0.           0.           2.          -0.36363636
   -0.18181818   0.63636364   0.        ]
 [ -0.           1.          -9.          -1.           1.
   -2.          -0.          -0.        ]
 [ -0.          -0.           1.          -0.          -0.04545455
    0.22727273  -0.04545455  -0.        ]
 [  0.           0.         -44.          -5.           3.
  -10.           0.           1.        ]]

Hasil :
[[  1.           0.           0.           2.          -0.36363636
   -0.18181818   0.63636364   0.        ]
 [ -0.           1.           0.          -1.           0.59090909
    0.04545455  -0.40909091  -0.        ]
 [ -0.          -0.           1.          -0.          -0.04545455
    0.22727273  -0.04545455  -0.        ]
 [  0.           0.         -44.          -5.           3.
  -10.           0.           1.        ]]


In [49]:
k = 2
l = 3
scale = 44

h12 = RowAdd(h11, k, l,scale)
print("Matriks awal:")
print(h11)
print("\nHasil :")
print(h12)

Matriks awal:
[[  1.           0.           0.           2.          -0.36363636
   -0.18181818   0.63636364   0.        ]
 [ -0.           1.           0.          -1.           0.59090909
    0.04545455  -0.40909091  -0.        ]
 [ -0.          -0.           1.          -0.          -0.04545455
    0.22727273  -0.04545455  -0.        ]
 [  0.           0.         -44.          -5.           3.
  -10.           0.           1.        ]]

Hasil :
[[ 1.          0.          0.          2.         -0.36363636 -0.18181818
   0.63636364  0.        ]
 [-0.          1.          0.         -1.          0.59090909  0.04545455
  -0.40909091 -0.        ]
 [-0.         -0.          1.         -0.         -0.04545455  0.22727273
  -0.04545455 -0.        ]
 [ 0.          0.          0.         -5.          1.          0.
  -2.          1.        ]]


In [51]:
k = 3
l = 3
scale = -1/5

h13 = RowScale(h12, k,scale)
print("Matriks awal:")
print(h12)
print("\nHasil :")
print(h13)

Matriks awal:
[[ 1.          0.          0.          2.         -0.36363636 -0.18181818
   0.63636364  0.        ]
 [-0.          1.          0.         -1.          0.59090909  0.04545455
  -0.40909091 -0.        ]
 [-0.         -0.          1.         -0.         -0.04545455  0.22727273
  -0.04545455 -0.        ]
 [ 0.          0.          0.         -5.          1.          0.
  -2.          1.        ]]

Hasil :
[[ 1.          0.          0.          2.         -0.36363636 -0.18181818
   0.63636364  0.        ]
 [-0.          1.          0.         -1.          0.59090909  0.04545455
  -0.40909091 -0.        ]
 [-0.         -0.          1.         -0.         -0.04545455  0.22727273
  -0.04545455 -0.        ]
 [-0.         -0.         -0.          1.         -0.2        -0.
   0.4        -0.2       ]]


In [52]:
k = 3
l = 0
scale = -2

h14 = RowAdd(h13, k, l, scale)
print("Matriks awal:")
print(h13)
print("\nHasil :")
print(h14)

Matriks awal:
[[ 1.          0.          0.          2.         -0.36363636 -0.18181818
   0.63636364  0.        ]
 [-0.          1.          0.         -1.          0.59090909  0.04545455
  -0.40909091 -0.        ]
 [-0.         -0.          1.         -0.         -0.04545455  0.22727273
  -0.04545455 -0.        ]
 [-0.         -0.         -0.          1.         -0.2        -0.
   0.4        -0.2       ]]

Hasil :
[[ 1.          0.          0.          0.          0.03636364 -0.18181818
  -0.16363636  0.4       ]
 [-0.          1.          0.         -1.          0.59090909  0.04545455
  -0.40909091 -0.        ]
 [-0.         -0.          1.         -0.         -0.04545455  0.22727273
  -0.04545455 -0.        ]
 [-0.         -0.         -0.          1.         -0.2        -0.
   0.4        -0.2       ]]


In [53]:
k = 3
l = 1
scale = 1

h15 = RowAdd(h14, k, l, scale)
print("Matriks awal:")
print(h14)
print("\nHasil :")
print(h15)

Matriks awal:
[[ 1.          0.          0.          0.          0.03636364 -0.18181818
  -0.16363636  0.4       ]
 [-0.          1.          0.         -1.          0.59090909  0.04545455
  -0.40909091 -0.        ]
 [-0.         -0.          1.         -0.         -0.04545455  0.22727273
  -0.04545455 -0.        ]
 [-0.         -0.         -0.          1.         -0.2        -0.
   0.4        -0.2       ]]

Hasil :
[[ 1.          0.          0.          0.          0.03636364 -0.18181818
  -0.16363636  0.4       ]
 [-0.          1.          0.          0.          0.39090909  0.04545455
  -0.00909091 -0.2       ]
 [-0.         -0.          1.         -0.         -0.04545455  0.22727273
  -0.04545455 -0.        ]
 [-0.         -0.         -0.          1.         -0.2        -0.
   0.4        -0.2       ]]


In [58]:
Inv = np.array([[0.03636364, -0.18181818,  -0.16363636,  0.4],
            [0.39090909,  0.04545455,  -0.00909091, -0.2       ],
            [-0.04545455,  0.22727273,  -0.04545455, -0        ],
            [ -0.2,        -0,   0.4,        -0.2,       ]])
B = np.array([[12],
              [15],
               [9],
               [5]])

hasil = np.dot(Inv,B)
print(hasil)

[[-1.76363626]
 [ 4.29090914]
 [ 2.4545454 ]
 [ 0.2       ]]


In [59]:
import numpy as np

A = np.array([[2,3,1,1,1,0,0,0], [1,1,5,1,0,1,0,0], [3,2,2,4,0,0,1,0], [4,1,3,2,0,0,0,1]]) 
print(A)

[[2 3 1 1 1 0 0 0]
 [1 1 5 1 0 1 0 0]
 [3 2 2 4 0 0 1 0]
 [4 1 3 2 0 0 0 1]]


In [60]:
A1 = A[0,:-4]
per1 = A1@hasil
print(per1)

[12.0000003]


In [61]:
A2 = A[1,:-4]
per2 = A2@hasil
print(per2)

[14.99999988]


In [62]:
A3 = A[2,:-4]
per3 = A3@hasil
print(per3)

[9.0000003]


In [63]:
A4 = A[3,:-4]
per4 = A4@hasil
print(per4)

[5.0000003]


SELESAI

### soal Waktu kuliah 3 variabel

In [ ]:
import numpy as np

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

# a = np.array([[2,2,1,1,0,0],[4,2,3,0,1,0],[1,3,-1,0,0,1]])
# print(a)
a = np.array([[1,1,0.5,0.5,0,0],[0,1,-0.5,1,-0.5,0],[0,0,1,5,-2,-2]])
print(a)

[[ 1.   1.   0.5  0.5  0.   0. ]
 [ 0.   1.  -0.5  1.  -0.5  0. ]
 [ 0.   0.   1.   5.  -2.  -2. ]]


In [ ]:
b = RowScale(a,2,1/2)
print(b)

[[ 1.   1.   0.5  0.5  0.   0. ]
 [ 0.   1.  -0.5  1.  -0.5  0. ]
 [ 0.   0.   0.5  2.5 -1.  -1. ]]


In [ ]:
c = RowAdd(b,2,1,1)
print(c)

[[ 1.   1.   0.5  0.5  0.   0. ]
 [ 0.   1.   0.   3.5 -1.5 -1. ]
 [ 0.   0.   0.5  2.5 -1.  -1. ]]


In [ ]:
d = RowAdd(c,2,0,-1)
print(d)

[[ 1.   1.   0.  -2.   1.   1. ]
 [ 0.   1.   0.   3.5 -1.5 -1. ]
 [ 0.   0.   0.5  2.5 -1.  -1. ]]


In [ ]:
f = RowScale(d,2,2)
print(f)

[[ 1.   1.   0.  -2.   1.   1. ]
 [ 0.   1.   0.   3.5 -1.5 -1. ]
 [ 0.   0.   1.   5.  -2.  -2. ]]


In [ ]:
f = RowScale(d,2,2)
print(f)

[[ 1.   1.   0.  -2.   1.   1. ]
 [ 0.   1.   0.   3.5 -1.5 -1. ]
 [ 0.   0.   1.   5.  -2.  -2. ]]


In [ ]:
b = np.array([[9],[17],[5]])

c = np.array([[-5.5,2.5,2],[3.5,-1.5,-1],[5,-2,-2]])

print(c@b)

[[3.]
 [1.]
 [1.]]


kiri jadikan identitas di kanan ngikut

definisi
teori tentang invers matriks
sifat sifat matriks
mencari matriks invers dengan eliminasi gauss jordan 
penuelesaian sistem persamaan linear menggunakan matriks invers
membiat soal 6 persamaan enam variabel cari solusinya pakai invers matriks

In [ ]:
a = np.array([[2,2,1,1,0,0],[4,2,3,0,1,0],[1,3,-1,0,0,1]])
print(a)

[[ 2  2  1  1  0  0]
 [ 4  2  3  0  1  0]
 [ 1  3 -1  0  0  1]]


In [ ]:
b = RowAdd(a,0,1,-2)
print(b)

[[ 2.  2.  1.  1.  0.  0.]
 [ 0. -2.  1. -2.  1.  0.]
 [ 1.  3. -1.  0.  0.  1.]]


In [ ]:
c = RowAdd(b,0,2,-1/2)
print(c)

[[ 2.   2.   1.   1.   0.   0. ]
 [ 0.  -2.   1.  -2.   1.   0. ]
 [ 0.   2.  -1.5 -0.5  0.   1. ]]


In [ ]:
d = RowScale(c,0,1/2)
print(d)

[[ 1.   1.   0.5  0.5  0.   0. ]
 [ 0.  -2.   1.  -2.   1.   0. ]
 [ 0.   2.  -1.5 -0.5  0.   1. ]]


In [ ]:
e = RowScale(d,1,-1/2)
print(e)

[[ 1.   1.   0.5  0.5  0.   0. ]
 [-0.   1.  -0.5  1.  -0.5 -0. ]
 [ 0.   2.  -1.5 -0.5  0.   1. ]]


In [ ]:
f = RowAdd(e,1,2,-2)
print(f)

[[ 1.   1.   0.5  0.5  0.   0. ]
 [-0.   1.  -0.5  1.  -0.5 -0. ]
 [ 0.   0.  -0.5 -2.5  1.   1. ]]


In [28]:
g = RowAdd(f,2,1,-1)
print(g)

[[ 1.   1.   0.5  0.5  0.   0. ]
 [-0.   1.   0.   3.5 -1.5 -1. ]
 [ 0.   0.  -0.5 -2.5  1.   1. ]]


In [29]:
h = RowAdd(g,2,0,1)
print(h)

[[ 1.   1.   0.  -2.   1.   1. ]
 [-0.   1.   0.   3.5 -1.5 -1. ]
 [ 0.   0.  -0.5 -2.5  1.   1. ]]


In [30]:
i = RowAdd(h,1,0,-1)
print(i)

[[ 1.   0.   0.  -5.5  2.5  2. ]
 [-0.   1.   0.   3.5 -1.5 -1. ]
 [ 0.   0.  -0.5 -2.5  1.   1. ]]


In [32]:
j = RowScale(i,2,-2)
print(j)

[[ 1.   0.   0.  -5.5  2.5  2. ]
 [-0.   1.   0.   3.5 -1.5 -1. ]
 [-0.  -0.   1.   5.  -2.  -2. ]]


In [31]:
b = np.array([[9],[17],[5]])
c = np.array([[-5.5,2.5,2],[3.5,-1.5,-1],[5,-2,-2]])
print(c@b)

[[3.]
 [1.]
 [1.]]
