# Determinan Matriks

## Definisi

Determinan matriks adalah selisih antara perkalian elemen-elemen pada diagonal utama dengan perkalian elemen-elemen pada diagonal sekunder. Determinan suatu matriks dapat dinotasikan dengan det(A) atau |A|.

Setiap matriks persegi ataupun bujur sangkar mempunyai nilai determinan. Nilai
determinan dari suatu matriks itu adalah skalar. Jika nilai determinan suatu matriks
sama dengan nol maka matriks tersebut disebut matriks singular.






## Sifat-sifat determinan

1. determinan matriks identitas adalah 1

Conoth 4 Matriks 

$$
A = \begin{bmatrix}
3 & 3 \\
5 & 2 \\
\end{bmatrix}
$$

$$
B = \begin{bmatrix}
2 & 3 & 3 \\
4 & 5 & 1 \\
6 & 3 & 3\\
\end{bmatrix}
$$

$$
C = \begin{bmatrix}
1 & 0 \\
0 & 1 \\
\end{bmatrix}
$$

$$
D = \begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{bmatrix}
$$

kita buktikan dari matrik C dam D

In [1]:
import numpy as np
a = np.array([[3,3], [5,2]])
b = np.array([[2,3,3],[4,5,1],[6,3,3]])
c = np.array([[1,0], [0,1]])
d = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(a)
print()
print(b)
print()
print(c)
print()
print(d)
print()
print(f"determinan dari matriks identitas c adalah : {np.linalg.det(c)}")
print(f"determinan dari matriks identitas d adalah : {np.linalg.det(d)}")
print()

[[3 3]
 [5 2]]

[[2 3 3]
 [4 5 1]
 [6 3 3]]

[[1 0]
 [0 1]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]

determinan dari matriks identitas c adalah : 1.0
determinan dari matriks identitas d adalah : 1.0



$$

2. det(c) = det(axb)
= det(a) x det(b)
=A x A^I
$$

dan 
$$

I = A x A^I

detI =det(A) x det(A^I)


det A^I = 1/detA
$$


kita buktikan 


In [2]:
a = np.array([[3,3], [5,2]])
B = np.linalg.inv(a)
detA = np.linalg.det(a)
detB = np.linalg.det(B)
print(f'determinan A : {detA.round()}')
print(f'determinan A invers : {detB.round()}')
C = detA * detB
print(f"det.A x det.B :",round(C))
print(a@B.round())

determinan A : -9.0
determinan A invers : -0.0
det.A x det.B : 1
[[3. 0.]
 [2. 0.]]


## EKspansi Konfaktor Determianan dari matriks 4 x 4

$$
A = \begin{bmatrix}
3 & 5 & -2 & 6 \\
1 & 2 & -1 & 1 \\
2 & 4 & 1 & 5 \\
3 & 7 & 5 & 3\\
\end{bmatrix}
$$

Penyelesaian: 

baris pertama akan kita jadikan koefisien, ketika kita membentuk matriks 3/3

$$
= \begin{bmatrix} 
3 & 5 & -2 & 6 \\      
1 & 2 & -1 & 1 \\
2 & 4 & 1 & 5 \\
3 & 7 & 5 & 3\\
\end{bmatrix} = + 3 
\begin{bmatrix}
2 & -1 & 1\\
4 & 1 & 5\\
7 & 5 & 3\\
\end{bmatrix}  = - 5
\begin{bmatrix}
1 & -1 & 1\\
2 & 1 & 3\\
3 & 5 & 3\\
\end{bmatrix} = + (-2)
\begin{bmatrix} 
1 & 2 & 1\\
2 & 4 & 3\\
3 & 7 & 3\\
\end{bmatrix} = - 6
\begin{bmatrix}
1 & 2 & -1\\
2 & 4 & 1 \\
3 & 7 & 5 \\
\end{bmatrix}
$$

baris pertama akan kita jadikan koefisien, ketika kita membentuk matriks 2/2

baris 1 kolom 1:
$$
\begin{bmatrix}
2 & -1 & 1\\
4 & 1 & 5\\
7 & 5 & 3\\
\end{bmatrix} = 2
\begin{bmatrix}
1 & 5\\ 
5 & 3\\
\end{bmatrix} = - (-1)
\begin{bmatrix}
4 & 5\\
7 & 3\\
\end{bmatrix} = + 1
\begin{bmatrix}
4 & 1\\
7 & 5\\
\end{bmatrix}
$$

$$
= 2(3 - 25) -(-1)(12 - 35) + 1(20 - 7)\\
= 2(-22) + 1(-23) + 1(13)\\
= -44 + 23 + 13\\
= -8
$$

baris 1 kolom 2:
$$
\begin{bmatrix}
1 & -1 & 1\\
2 & 1 & 3\\
3 & 5 & 3\\
\end{bmatrix} = 1
\begin{bmatrix}
1 & 3\\
5 & 3\\
\end{bmatrix} = -(-1)
\begin{bmatrix}
2 & 3\\
3 & 3\\
\end{bmatrix} = + 1
\begin{bmatrix}
2 & 1\\
3 & 5\\
\end{bmatrix}
$$

$$
= 1(3 - 15) - (-1)(6 - 9) + 1(10 - 3)\\
= 1(-12) - 1(-3) + 1(7)\\
= -12 + 3 + 7\\
= -2
$$

baris 1 kolom 3:
$$
\begin{bmatrix} 
1 & 2 & 1\\
2 & 4 & 3\\
3 & 7 & 3\\
\end{bmatrix} = 1
\begin{bmatrix}
4 & 3\\
7 & 3\\
\end{bmatrix} = -2 
\begin{bmatrix}
2 & 3\\
3 & 3\\
\end{bmatrix} = + 1
\begin{bmatrix}
2 & 4\\
3 & 7\\
\end{bmatrix}
$$

$$
= 1(12 - 21) - (-2)(6 - 9) + 1(14 - 12)\\
= 1(9) + 2(-3) + 1(2)\\
= 9 + (-6) + 2\\
= 5
$$

baris 1 kolom 4:
$$
\begin{bmatrix}
1 & 2 & -1\\
2 & 4 & 1 \\
3 & 7 & 5 \\
\end{bmatrix} = 1
\begin{bmatrix}
4 & 1\\
7 & 5\\
\end{bmatrix} = -2
\begin{bmatrix}
2 & 1\\
3 & 5\\ 
\end{bmatrix} = +(-1)
\begin{bmatrix}
2 & 4\\
3 & 7\\
\end{bmatrix}
$$

$$
= 1(20 - 7) -2(10 - 3) +(-1)(14 - 12)\\
= 1(3) -2(7) +(-1)(2)\\
= 3 - 14 - 2\\
= -13
$$


Hasilnya:

$$
= \begin{bmatrix} 
3 & 5 & -2 & 6 \\      
1 & 2 & -1 & 1 \\
2 & 4 & 1 & 5 \\
3 & 7 & 5 & 3\\
\end{bmatrix} 
$$

$$
\begin{bmatrix}
2 & -1 & 1\\
4 & 1 & 5\\
7 & 5 & 3\\
\end{bmatrix}  = + 3\\ 
$$

$$
3(-8)
$$

$$
\begin{bmatrix}
1 & -1 & 1\\
2 & 1 & 3\\
3 & 5 & 3\\
\end{bmatrix} = - 5\\
$$

$$
-5(-2)
$$

$$
\begin{bmatrix} 
1 & 2 & 1\\
2 & 4 & 3\\
3 & 7 & 3\\
\end{bmatrix} = + (-2)\\
$$

$$
+(-2)(5)
$$

$$
\begin{bmatrix}
1 & 2 & -1\\
2 & 4 & 1 \\
3 & 7 & 5 \\
\end{bmatrix} = - 6\\ 
$$

$$
-6(-13)
$$


$$
= 3(-8) - 5(-2) + (-2)(5) - 6(-13)\\
= -24 + 10 + (-10) - (-78)\\
= 54
$$

Link referensi belajar det matriks 4x4:

https://www.youtube.com/watch?v=fWzUwrt1Z0s