# Eliminasi Gauss

Eliminasi gauss adalah metode untuk operasi nilai-nilai dalam matriks, untuk membuat matriks lebih sederhana lagi. Metode eliminasi gaus dikembangkan dari metode eliminasi, dengan cara menghilangkan atau mengurangi jumlah variabel, untuk mendapatkan nilai variabel bebas.

### Penggunaa Eliminasi Gauss

Penggunaan Eliminasi Gauss yaitu mengubah persamaan linear menjadi bentuk matriks, kemudian diubah ke bentuk Eselon Baris melalui Operasi Baris Elementer. Setelah itu bentuk matriks diselesaikan dengan substitusi balik. Eliminasi Gauss ini berasal dari operasi matematika pada baris matriks yang dilanjutkan sampai tersisa satu variabel.

### RowSwap

RowSwap adalah operasi dasar pada matriks yang melibatkan pertukaran dua baris. Dalam operasi ini, dua baris pada matriks ditukar posisinya. Operasi row swap sering digunakan dalam proses Eliminasi Gauss


Contoh jika memiliki soal Matrix berikut

In [1]:
import numpy as np
A=np.array([[8,9,1,19],
            [1,2,3,9],
            [2,1,1,5]])
print(A)

[[ 8  9  1 19]
 [ 1  2  3  9]
 [ 2  1  1  5]]


Lalu kita ingin menukar baris pertama dengan baris kedua, maka setelah operasi RowSwap, matriks akan menjadi:

In [2]:
def RowSwap(A,k,l):
# =============================================================================
#     A adalah sebuah NumPy array.  RowSwap akan menghasilkan duplicate dari 
#     array dengan baris k dan l di tukar
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

RSW=np.array([[8,9,1,19],
              [1,2,3,9],
              [2,1,1,5]])

k = 0
l = 1

# Memanggil fungsi RowSwap dan menampilkan outputnya
result = RowSwap(RSW, k, 1)
print("Matriks awal:")
print(RSW)
print("\nMatriks setelah RowSwap:")
print(result)

Matriks awal:
[[ 8  9  1 19]
 [ 1  2  3  9]
 [ 2  1  1  5]]

Matriks setelah RowSwap:
[[ 1.  2.  3.  9.]
 [ 8.  9.  1. 19.]
 [ 2.  1.  1.  5.]]


In [3]:
A1= RowSwap(A,0,1)
print(A1)

[[ 1.  2.  3.  9.]
 [ 8.  9.  1. 19.]
 [ 2.  1.  1.  5.]]


### RowAdd

RowAdd adalah operasi dasar pada matriks yang melibatkan penambahan hasil perkalian satu baris dengan suatu skalar (bilangan konstan) terhadap baris lainnya. Dalam operasi ini, setiap elemen pada suatu baris akan ditambahkan dengan hasil perkalian skalar tersebut terhadap elemen pada baris lain.

Misalnya, jika kita memiliki matriks berikut:

In [4]:
RA=np.array([[8,9,1,20],
             [1,2,13,9],
             [2,11,3,5]])
print(RA)

[[ 8  9  1 20]
 [ 1  2 13  9]
 [ 2 11  3  5]]


Dan kita ingin menambahkan dua kali baris pertama ke baris kedua, maka setelah operasi row add, matriks akan menjadi:

In [5]:
def RowAdd(A,k,l,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowAddp akan menghasilkan duplicate dari 
#     array dengan baris k akan di kali dengan scalar bukan 0. lalu baris nilai
#     baris l akan di tambah dengan nilai baris k yang sudah dikalikan  
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

RA=np.array([[8,9,1,20],
             [1,2,13,9],
             [2,11,3,5]])

k = 0
l = 1
scale = 2

# Memanggil fungsi RowAdd dan menampilkan outputnya
result = RowAdd(RA, k, l, scale)
print("Matriks awal:")
print(RA)
print("\nMatriks setelah RowAdd:")
print(result)

Matriks awal:
[[ 8  9  1 20]
 [ 1  2 13  9]
 [ 2 11  3  5]]

Matriks setelah RowAdd:
[[ 8.  9.  1. 20.]
 [17. 20. 15. 49.]
 [ 2. 11.  3.  5.]]


Maka dari hasil berikut:

\begin{align*} 8x_1 + 9x_2 + x_3 = 19 \\

x_1 + 2x_2 + 3x_3 = 9 \\

2x_1 + x_2 + x_3 \end{align*}

Hasil setelah dibulatkan:

\begin{align*} x_1 + 2x_2 + 3x_3 = 9 \\

x_2 + 3x_3 = 8 \\

x_3 = 2 \end{align*}
