# MATRIKS

## Definisi Matriks

### Penjelasan tentang Matriks 
Matriks adalah suatu susunan bilangan real atau bilangan kompleks (atau elemen-elemen) yang disusun dalam baris dan kolom sehingga membentuk jajaran persegi panjang.[1]https://fti.ars.ac.id/blog/content/matriks--jenis-jenis-matriks

contoh:

$$\begin{split}A = \begin{bmatrix} 
3 & 1 & 0 \\ 
5 & 2 & 1 \\ 
0 & 2 & 3
\end{bmatrix}\end{split}

\begin{split}c = \begin{bmatrix} 
1 & 2  \\
3 & 4  \\
1 & 0
\end{bmatrix}\end{split}
$$

### Jenis-jenis Matriks 

Jenis-jenis matrik yaitu Matrik nol, matrik diagonal, matrik skalar, matrik simetris, matrik identitas, matrik segitiga atas, matrik segitiga bawah, matrik transpose.

a. Matrik Nol adalah matrik yang semua elemennya penyusunnya nol:

$$
\begin{split}I = \begin{bmatrix}
0 & 0 & 0\\
0 & 0 & 0 \\
0 & 0 & 0
\end{bmatrix}\end{split}
$$

b. Matrik Diagonal adalah suatu matrik yang dimana elemen-elemen diagonalnya mempunyai nilai tidal sama dengan nol dan elemen-elemen selain diagonal bernilai nol:

$$
\begin{split}A = \begin{bmatrix}
1 & 0 & 0 \\
0 & 2 & 0 \\
0 & 0 & 3
\end{bmatrix}\end{split}
$$

c. Matrik Skalar adalah matrik yang dimana elemen-elemen diagonalnya bernilai sama dan elemen-elemen selain diagonal bernilai nol:

$$
\begin{split}A = \begin{bmatrix}
3 & 0 & 0 \\
0 & 3 & 0 \\
0 & 0 & 3
\end{bmatrix}\end{split}
$$

d. Matriks simetris adalah suatu matrik yang jika elemen-elemen matriks A yang terletak pada baris dan kolom yang sama memiliki nilai yang sama dengan elemen-elemen matriks A yang terletak pada baris dan kolom yang berlawanan:

$$
\begin{split}A = \begin{bmatrix}
3 & 1 & 2 \\
1 & 4 & 0 \\
2 & 0 & 3
\end{bmatrix}\end{split}
$$

e. Matrik Identitas adalah suatu matrik yang elemen-elemen diagonalnya mempunyai nilai 1, sedangkan selain elemen pada diagonal bernilai nol:

$$
\begin{split}A = \begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}\end{split}
$$

f. Matrik Segitiga Atas adalah suatu matrik yang elemen-elemennya dibawah diagonal adalah nol:

$$
\begin{split}A = \begin{bmatrix}
-2 & 6 & 1 \\
0 & 2 & 3 \\
0 & 0 & -2
\end{bmatrix}\end{split}
$$

g. Matrik Segitiga Bawah adalah suatu matrik yang elemen-elemennya diatas diagonal adalah nol:

$$
\begin{split}A = \begin{bmatrix}
-2 & 0 & 0 \\
3 & -2 & 0 
\end{bmatrix}\end{split}
$$

h. Matrik Transpose merupakan matrik yang diperoleh dari memindahkan elemen-elemen baris menjadi kolom atau sebaliknya:

Selelum Transpose:

$$
\begin{split}A = \begin{bmatrix}
1 & 2 & 3 \\ 
4 & 5 & 6
\end{bmatrix}\end{split}
$$

Transpose:

$$
\begin{split}A^T = \begin{bmatrix} 
1 & 4  \\
2 & 5  \\
3 & 6
\end{bmatrix}\end{split}
$$






 


### Penjelasan Numpy 

NumPy (Numerical Python) adalah library dalam bahasa pemrograman Python yang digunakan untuk memanipulasi dan meanalisis data numerik. Numpy menyediakan fungsi yang siap pakai untuk memudahkan melakukan perhitungan saintifik seperti matriks, aljabar,dan statistik.

In [1]:
import numpy as np

### Ordo/Ukuran/Order dari suatu matriks

Ordo/ukuran dari suatu matriks ditentukan oleh banyaknya baris dan kolom yang dimiliki oleh matriks tersebut. Contoh: Matriks A pada contoh di atas meniliki dua buah baris dan dua buah kolom, sehingga kita katakana matriks A berordo 2 x 2.[3] https://fti.ars.ac.id/blog/content/matriks--jenis-jenis-matriks


Contoh Matriks berordo 2 x 2

$$
\begin{split}A = \begin{bmatrix} 
1 & 2  \\
3 & 4  \\
\end{bmatrix}\end{split}
$$

In [2]:
# import library numpy

import numpy as np

Gunakan np.array([matriks]) untuk membuat matriks dengan nilai yang dpat diisi sendiri

In [3]:
import numpy as np 
A = np.array([[1,3],[2,1]])
B = np.array([[3,0,4],[-1,-2,1]])
C = np.array([[-2,1],[4,1]])
D = np.array([[2],[6]])

print("A")
print(A,"\n")

print("B")
print(B,"\n")

print("C")
print(C,"\n")

print("D")
print(D,"\n")


A
[[1 3]
 [2 1]] 

B
[[ 3  0  4]
 [-1 -2  1]] 

C
[[-2  1]
 [ 4  1]] 

D
[[2]
 [6]] 



Gunakan np.random.randint(n,seze(=i,j) untuk membuat matriks dengan nilai int acak 0-n dan memeiliki baris i dan kolom j

In [4]:
E = np.random.randint(10,size=(2,2))
F = np.random.randint(10,size=(3,2))
G = np.random.randint(10,size=(3,3))
print("F")
print(E,"\n")

print("E")
print(F,"\n")

print("G")
print(G,"\n")

F
[[7 6]
 [5 9]] 

E
[[9 1]
 [8 6]
 [8 7]] 

G
[[4 0 7]
 [8 7 3]
 [8 3 2]] 



Untuk mengecek panjang baris dan kolom dapat menggunakan np.shape atau len

In [5]:
print("baris dan kolom matriks A\n",np.shape(A))
print("baris dan kolom matriks B\n", len(B),len(B[0]))

baris dan kolom matriks A
 (2, 2)
baris dan kolom matriks B
 2 3


## Operasi-operasi matriks

matriks yang ukurannya sama dapat dijumlahkan.Hasilnya adalah semua elemen yang bersesuaian ditambhkan dan ditulis dalam bentuk.


(A+C) = a+c

A+0=A dimana 0 matriks nol

A+B=B+A

(A+B)+C=A+(B+C)

## Operasi Matriks

### Penjumlahan 

syarat matriks agar bisa dijumlahkan adalah dua matriks harus memiliki ordo yang sama dengan kata  lain seperti matrik A dan Matrik B mempunyai ordo yang sama. Hasil penjumlahannya berupa matrik C dengan ordo yang sama dengan matrik A dan B.

1. Sifat komutatif Pada sifat ini berlaku A + B = B + A.

2. Sifat asosiatif Pada sifat ini berlaku (A + B) + C = A +(B + C)

3. Matriks nol Pada sifat ini berlaku A + 0 = A

4. Jika dijumlahkan dengan lawannya akan menghasilkan matriks nol, yaitu A + (-A) = 0.

[4]https://www.pijarbelajar.id/blog/operasi-matriks-penjumlahan-pengurangan-dan-perkalian-beserta-contoh-soalnya. Contohnya seperti matriks di bawah ini. 


In [6]:
print("Matrik A")
print(A,"\n")

print("Matrik C")
print(C,"\n")

ac = A+C
print("hasil matriks A+C =")
print(ac,)

Matrik A
[[1 3]
 [2 1]] 

Matrik C
[[-2  1]
 [ 4  1]] 

hasil matriks A+C =
[[-1  4]
 [ 6  2]]


### Pengurangan 

Konsep pengurangan pada operasi matriks sama seperti cara pengerjaan penjumlahan, jadi tinggal mengurangkan masing-masing baris sesuai dengan urutannya. 
Syarat pengurangan matriks pun sama dengan penjumlahan, yaitu kedua matriks harus memiliki ordo yang sama sehingga bisa dioperasikan.[5]https://www.pijarbelajar.id/blog/operasi-matriks-penjumlahan-pengurangan-dan-perkalian-beserta-contoh-soalnya

Dibawah ini merupakan contoh operasi pengurangan matriks : 

In [7]:

print("Matrix A")
print(A,"\n")

print("Matrix C")
print(C,"\n")

ac = A - C
print("hasil of A-C =")
print(ac)


Matrix A
[[1 3]
 [2 1]] 

Matrix C
[[-2  1]
 [ 4  1]] 

hasil of A-C =
[[ 3  2]
 [-2  0]]


### Perkalian 

#### Operasi Perkalian Matriks dengan Bilangan Real (Skalar)

Perkalian matriks dengan bilangan real (skalar) tidak memiliki persyaratan. Jadi, semua matriks dengan ordo apapun bisa dikalikan dengan bilangan real (skalar).[6]https://www.pijarbelajar.id/blog/operasi-matriks-penjumlahan-pengurangan-dan-perkalian-beserta-contoh-soalnya

Dibawah ini merupakan contoh operasi perkalian matriks dengan bilangan saklar :



In [8]:
# perkalian dengan saklar 

# J adalah saklar dan A adalah matriks

J = 4
JA = J * A
print("matriks A")
print(A,"\n")
print("saklar J")
print(J,"\n")
print("hasil perkalian matriks A dengan saklar J")
print(JA,"\n")


matriks A
[[1 3]
 [2 1]] 

saklar J
4 

hasil perkalian matriks A dengan saklar J
[[ 4 12]
 [ 8  4]] 



#### Perkalian Dua Matriks

1) Sifat tidak komutatif

(AB)C = A(BC)

2) Pada sifat distributif ini berkaitan dengan operasi penjumlahan matriks. 

A(B + C) = AB + AC

Berikut contohnya:

X (Y + Z) = XY + XZ

(Y + Z) X = YX + ZX 

[7]https://www.pijarbelajar.id/blog/operasi-matriks-penjumlahan-pengurangan-dan-perkalian-beserta-contoh-soalnya


In [9]:
a = np.array(([1,2,3],[4,5,6],[4,5,6]))
b = np.array(([3,2,1],[-1,-2,-3],[7,5,6]))

hasil = np.dot(a,b)

print('Ini Matrik a: ')
print(a)
print()
print('Ini Matrik b: ')
print(b)
print()
print('Hasil a x b: ')
print(hasil)

Ini Matrik a: 
[[1 2 3]
 [4 5 6]
 [4 5 6]]

Ini Matrik b: 
[[ 3  2  1]
 [-1 -2 -3]
 [ 7  5  6]]

Hasil a x b: 
[[22 13 13]
 [49 28 25]
 [49 28 25]]


## Tugas perkalian Dua Matriks 

### Perkalian dua Matriks menggunakan perulangan 

In [10]:
listA = [[2,4],[2,5],[2,3]]

listB = [[3,5,1],[1,6,3]]
  
print("Matriks A",listA,"\n")
print("MAtriks B",listB,"\n")

print("panjang baris dan kolom")
print("Matriks A")
print(len(listA),len(listA[0]),"\n")
print("Matriks B")
print(len(listB),len(listB[0]),"\n")

# n adalah panjang baris matrix listA
n = len(listA)

# adalah panjang kolom matrix listA dan panjang baris matrix listB
m = len(listA[0])

# p adalah panjang baris matrix listB
p = len(listB[0])

hasil = []
# perulangan terjadi sebanyak panjang baris listA
for i in range(0,n):
  hasil1 = []
  # perulangan terjadi sebanyak panjang baris listB
  for j in range(0,p):
    jumlah = 0
    for k in range(0,m):
      jumlah += listA[i][k] * listB[k][j]
    hasil1.append(jumlah)
  hasil.append(hasil1)
print("hasil dari perkalian matrix :" "\n")
print(hasil,"\n")

Matriks A [[2, 4], [2, 5], [2, 3]] 

MAtriks B [[3, 5, 1], [1, 6, 3]] 

panjang baris dan kolom
Matriks A
3 2 

Matriks B
2 3 

hasil dari perkalian matrix :

[[10, 34, 14], [11, 40, 17], [9, 28, 11]] 



### Perkalian dua matriks dengan library numpy

In [11]:
MatriksA = np.array(([2,4],[2,5],[2,3]))
MatriksB = np.array(([2,5,1],[1,6,3]))

print(MatriksA,"\n")
print(MatriksB,"\n")

dot1 = np.dot(MatriksA,MatriksB)
dot2 = MatriksA.dot(MatriksB)

print(dot1,"\n")
print(dot2,"\n")

[[2 4]
 [2 5]
 [2 3]] 

[[2 5 1]
 [1 6 3]] 

[[ 8 34 14]
 [ 9 40 17]
 [ 7 28 11]] 

[[ 8 34 14]
 [ 9 40 17]
 [ 7 28 11]] 



In [12]:
matriksA= np.array((([2,1],[1,1])))
matrixB=np.array((([1,0],[0,1])))

dot1 = np.dot(MatriksA,MatriksB)
dot2 = MatriksA.dot(MatriksB)

print(dot1,"\n")
print(dot2,"\n")

[[ 8 34 14]
 [ 9 40 17]
 [ 7 28 11]] 

[[ 8 34 14]
 [ 9 40 17]
 [ 7 28 11]] 

