# Determinan Matriks

## Definisi

Determinan matriks adalah suatu fungsi tertentu yang menghubungkan suatu bilangan riil
dengan suatu matriks bujur sangkar. Determinan suatu matriks dapat dinotasikan dengan det(A) atau |A|.

Setiap matriks persegi ataupun bujur sangkar mempunyai nilai determinan. Nilai
determinan dari suatu matriks itu adalah skalar. Jika nilai determinan suatu matriks
sama dengan nol maka matriks tersebut disebut matriks singular.


## Sifat-sifat determinan

1. determinan matriks identitas adalah 1

Conoth 4 Matriks 

$$
A = \begin{bmatrix}
3 & 3 \\
5 & 2 \\
\end{bmatrix}
$$

$$
B = \begin{bmatrix}
2 & 3 & 3 \\
4 & 5 & 1 \\
6 & 3 & 3\\
\end{bmatrix}
$$

$$
C = \begin{bmatrix}
1 & 0 \\
0 & 1 \\
\end{bmatrix}
$$

$$
D = \begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{bmatrix}
$$

kita buktikan dari matrik C dam D

In [1]:
import numpy as np
a = np.array([[3,3], [5,2]])
b = np.array([[2,3,3],[4,5,1],[6,3,3]])
c = np.array([[1,0], [0,1]])
d = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(a)
print()
print(b)
print()
print(c)
print()
print(d)
print()
print(f"determinan dari matriks identitas c adalah : {np.linalg.det(c)}")
print(f"determinan dari matriks identitas d adalah : {np.linalg.det(d)}")
print()

[[3 3]
 [5 2]]

[[2 3 3]
 [4 5 1]
 [6 3 3]]

[[1 0]
 [0 1]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]

determinan dari matriks identitas c adalah : 1.0
determinan dari matriks identitas d adalah : 1.0



$$

2. det(c) = det(axb)
= det(a) x det(b)
=A x A^I
$$

dan 
$$

I = A x A^I

detI =det(A) x det(A^I)


det A^I = 1/detA
$$


kita buktikan 


In [2]:
a = np.array([[3,3], [5,2]])
B = np.linalg.inv(a)
detA = np.linalg.det(a)
detB = np.linalg.det(B)
print(f'determinan A : {detA.round()}')
print(f'determinan A invers : {detB.round()}')
C = detA * detB
print(f"det.A x det.B :",round(C))
print(a@B.round())

determinan A : -9.0
determinan A invers : -0.0
det.A x det.B : 1
[[3. 0.]
 [2. 0.]]


## EKspansi Konfaktor



$$
A = \begin{bmatrix}
3 & 5 & -2 & 6 \\
1 & 2 & -1 & 1 \\
2 & 4 & 1 & 5 \\
3 & 7 & 5 & 3\\
\end{bmatrix}
$$


Penyelesaian:

$$
= \begin{bmatrix}
3 & 5 & -2 & 6 \\
1 & 2 & -1 & 1 \\
2 & 4 & 1 & 5 \\
3 & 7 & 5 & 3\\
\end{bmatrix}
$$

baris pertama ditukar dengan baris kedua
$$
= \begin{bmatrix}
1 & 2 & -1 & 1 \\
3 & 5 & -2 & 6 \\
2 & 4 & 1 & 5 \\
3 & 7 & 5 & 3\\
\end{bmatrix}
$$

-3 kali baris pertama ditambahakan ke baris kedua

$$
= \begin{bmatrix}
1 & 2 & -1 & 1 \\
0 & -1 & 1 & 3 \\
2 & 4 & 1 & 5 \\
3 & 7 & 5 & 3\\
\end{bmatrix}
$$

-2 kali baris pertama ditambhakan ke baris ketiga

$$
= \begin{bmatrix}
1 & 2 & -1 & 1 \\
0 & -1 & 1 & 3 \\
0 & 0 & 3 & 3 \\
3 & 7 & 5 & 3\\
\end{bmatrix}
$$

-3 kali baris pertama ditambahkan ke baris
keempat

$$
= \begin{bmatrix}
1 & 2 & -1 & 1 \\
0 & -1 & 1 & 3 \\
0 & 0 & 3 & 3 \\
0 & 1 & 8 & 0\\
\end{bmatrix}
$$





Ekspansi kolom pertama 

$$
= -(-1)^{1+1} (-1) = \begin{bmatrix}
-1 & 1 & 3 \\
0 & 3 & 3 \\
1 & 8 & 0 \\
\end{bmatrix}
$$

Baris pertama ditambahkan ke baris ketiga

$$
= \begin{bmatrix}
-1 & 1 & 3 \\
0 & 3 & 3 \\
1 & 9 & 3 \\
\end{bmatrix}
$$

Ekspansi kofaktor kolom pertama
$$
= -(-1)^{1+1} (-1) = \begin{bmatrix}
3 & 3 \\
9 & 3 \\
\end{bmatrix}
$$

=9 - 27

= -18
